repos:
  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # Python linting: flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # fixed release tag
    hooks:
      - id: flake8

  # Python formatting: black
  - repo: https://github.com/psf/black
    rev: 23.12.0  # fixed release tag
    hooks:
      - id: black
        language_version: python3

  # JavaScript / TypeScript linting: eslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0  # fixed release tag
    hooks:
      - id: eslint

  # Go linting: golangci-lint
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.0  # fixed release tag
    hooks:
      - id: golangci-lint
        args: ["run"]
